[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Frauens"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
